# Generated by Django 3.2.7 on 2021-10-03 16:26

import datetime
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=75)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('fecha_de_nacimiento', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('sexo', models.CharField(default='M', max_length=1)),
                ('fecha_ingreso', models.DateField(default=datetime.date.today)),
                ('numero_de_empleado', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=50)),
                ('jefe', models.CharField(max_length=30)),
                ('area_operacional', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('ventas', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=2000, null=True)),
                ('numero_celular', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'CustomUsers',
            },
        ),
    ]
